### ISSUE TITLE
绘制问题

### ISSUE THREAD

**Issue by PainterHu** [Giftedcat/Waveform#1]
您好，就是从左往右更新数据时，波形之间有个空白的间距，是哪段代码实现的。非常感谢

**Comment by Giftedcat** [comment]
WaveView类第224行drawWaveLineLoop函数
如果不需要中间的空白间距，把if else去掉，只要else就好了

**Comment by PainterHu** [comment]
看到了，您还写了注释，我没留意看，谢谢您的回答

**Comment by PainterHu** [comment]
> WaveView类第224行drawWaveLineLoop函数
> 如果不需要中间的空白间距，把if else去掉，只要else就好了

看到了，您还写了注释，我没留意看，谢谢您的回答
